# University Admission Prediction + QS-Aware Top-K Recommender

## Objetivo

	•	Predecir admitted (0/1) con features académicas + contexto.
	•	Enriquecer con qs_score por (university_clean, mapped_major).
	•	Resolver degree → mapped_major (1 a N) duplicando filas cuando aplique.
	•	Recomendación Top-K usando probabilidad del modelo + QS como señal auxiliar.

### Imports

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sdv.single_table import CTGANSynthesizer
from sdv.metadata import SingleTableMetadata
from sklearn.preprocessing import LabelEncoder

# Environment

In [2]:
import sys
from pathlib import Path

NOTEBOOK_DIR = Path().resolve()
PROJECT_ROOT = NOTEBOOK_DIR

# Sube hasta encontrar la carpeta que contiene "src"
for _ in range(6):
    if (PROJECT_ROOT / "src").exists():
        break
    PROJECT_ROOT = PROJECT_ROOT.parent

print("NOTEBOOK_DIR:", NOTEBOOK_DIR)
print("PROJECT_ROOT:", PROJECT_ROOT)
print("SRC_EXISTS:", (PROJECT_ROOT / "src").exists())
print("SRC_INIT_EXISTS:", (PROJECT_ROOT / "src" / "__init__.py").exists())

sys.path.insert(0, str(PROJECT_ROOT))
print("sys.path[0]:", sys.path[0])

NOTEBOOK_DIR: /Users/danimorera/Documents/Portfolio/FLRecomendator/notebooks
PROJECT_ROOT: /Users/danimorera/Documents/Portfolio/FLRecomendator
SRC_EXISTS: True
SRC_INIT_EXISTS: True
sys.path[0]: /Users/danimorera/Documents/Portfolio/FLRecomendator

# Imports and Global Configuration

In [3]:
from src.config import RAW_DIR, RANDOM_STATE
from src.utils import load_excel_safe, load_qs_excel

RAW_DIR, RANDOM_STATE

(PosixPath('/Users/danimorera/Documents/Portfolio/FLRecomendator/data/raw'),
 42)

# Data Sources

In [4]:
STUDENTS_PATH = RAW_DIR / "Five Lands Stats.xlsx"
QS_PATH = RAW_DIR / "University Ranking by Major 2025.xlsx"

STUDENTS_PATH.exists(), QS_PATH.exists()

df_students_raw = load_excel_safe(STUDENTS_PATH)
df_qs_raw = load_qs_excel(QS_PATH)

In [5]:
df_students_raw.columns

Index(['TYPE OF STUDENT', 'LAST YEAR INSTITUTION', 'SCHOOL\nCURRICULUM',
       'SCHOOL\nGRADE', 'GPA', 'TOEFL \n(MAX)', 'SAT\n(SUPERSCORE)',
       'PROFILE\n(4-16)', 'PEAK', 'Unnamed: 9', 'UNIVERSITY', 'COUNTRY',
       'DEGREE', 'AREA OF STUDY', 'Unnamed: 14', 'ADMISSION', 'CURRENCY',
       'TUITION\nYEAR', 'AID\nYEAR', 'AID\nYEAR (EUR)', 'AID\nYEAR (USD)',
       'FINAL TUITION\nYEAR', 'FINAL TUITION\nYEAR (EUR)',
       'FINAL TUITION\nYEAR (USD)', '% AID', 'Unnamed: 25', 'Unnamed: 26',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29'],
      dtype='object')

# Tratamiento Students

In [6]:
from src.cleaning_students import clean_students_schema, null_students_schema

df_students = clean_students_schema(df_students_raw)
df_students = null_students_schema(df_students)

In [7]:
df_students.head()

,school_curriculum,school_grade,gpa,toefl,sat,profile_score,peak,university,country,degree,admitted,sat_required
0,BASE 7,33.0,3.5,102,1000.0,9,0,AMSTERDAM UNIVERSITY OF APPLIED SCIENCE,NETHERLANDS,"Business, Communication, International Busines...",1.0,1
1,BASE 7,33.0,3.5,102,1000.0,9,0,IE UNIVERSITY MADRID CAMPUS,SPAIN,"Business, Communication, International Busines...",1.0,1
2,BASE 7,33.0,3.5,102,1000.0,9,0,UNIVERSIDAD EUROPEA,SPAIN,"Business, Communication, International Busines...",1.0,1
3,BASE 7,33.0,3.5,102,1000.0,9,0,SAINT LOUIS UNIVERSITY MADRID,SPAIN,"Business, Communication, International Busines...",1.0,1
4,BASE 7,33.0,3.5,102,1000.0,9,0,CUNEF UNIVERSIDAD,SPAIN,"Business, Communication, International Busines...",1.0,1

# Tratamiento QS

Lo hago de esta manera debido a que es un ExcelFile y necesito iterar sobre sus sheets

In [8]:
from src.cleaning_qs import initial_clean_qs_schema, augmentation_qs_schema, clean_qs_schema

df_qs = clean_qs_schema(augmentation_qs_schema(initial_clean_qs_schema(df_qs_raw)))

# Mapping df_qs, df_students (degree / universities)

In [9]:
from src.merge_students_qs import university_mapping, degree_mapping, show_degree_mapping

df_students["university"] = [university_mapping(university) for university in df_students["university"]]
df_qs["university"] = [university_mapping(university) for university in df_qs["university"]]

df_students, df_qs_degrees = degree_mapping(df_students)

### Resultado asignacion de variable degree

In [10]:
show_degree_mapping(df_qs_degrees)

Computer Science (15):
  - Computer Science
  - Electronic Engineering with Computer Systems H6G4
  - Business, Cognitive Science, Computer Animation, Computer Science & Web Design, Data Science & Data Analytics, Economics, Engineering, Management
  - Computer Science & Mathematics
  - Mathematics & Computer Science
  - Computer Science and Mathematics with Industrial Experience
  - Computer Engineering
  - Comptuter Science and Artificial Intellience
  - Electrical & Computer Engineering
  - Computer Science and Business
  - Business Information Technology
  - Computing Science & Mathematics
  - Mathematics and Computer Science 3FT BEng (Hon)
  - Mathematics - Computer Science, B.S.
  - Computer Science & Web Design, Engineering,

Data Science (9):
  - Data & Business Analytics
  - Biosystems Analytics & Technology
  - Ingeniería de Telecomunicaciones  y Business Analytics
  - Business Analytics
  - ADE+ Business Analytics
  - Doble Grado ADE y Ciencias de Datos
  - BBA & Data Analytics
  - Data Sciences
  - Data Science and Analytics

Engineering - Mechanical (16):
  - Mechanical Engineering
  - BS in Aerospace Engineering
  - Aerospace Engineering
  - Mechanical Engineering / Automotive
  - Mechanical Engineering (Automotive Engineering)
  - Automotive Engineering
  - Aerospace & Astrophysics
  - Bachelor Automotive Engineering
  - Bachelor in Automotive Engineering
  - Mechanical Engineering (Automotive Engineering) Foundation (H322)
  - Mechanical Engineering with a Foundation Year (H301)
  - Mechanical Engineering with an Integrated Foundation Year (H109)
  - Mechanical Engineering BEng(Hons) with integrated foundation year
  - B.Sc. Mechanical Engineering (International)
  - MEng Aerospace with a year in industry
  - Aerospace

Engineering - Electrical (3):
  - Electrical and Electronic Engineering H606
  - Mechatronics and Robotics HH36
  - Electrical & Electronic Engineering H600

Engineering - Chemical (5):
  - Bioprocessing of New Medicines (Science and Engineering) BSc
  - Chemical Engineering and Biotechnology
  - Chemical Engineering, BS
  - Biochemical Engineering
  - Applied Science - Chemistry & Chemical Engineering

Earth & Marine Sciences (1):
  - Marine Biology

Engineering & Technology (29):
  - BS in Agricultural and Medical
Biotechnology
  - Biotechnology
  - Engineering
  - Physics, Mathematics and Engineering
  - Psychology and Technology
  - Molecular Bioengineering
  - BSc Biological Sciences (Biotechnology)
  - BS Biomedical Engineering
  - Bioengineering, BS
  - General Engineering
  - Industrial Engineering
  - Engineering Business & Management
  - Industrial Engineering & Management
  - Advanced Technology
  - Music Technology
  - Music Technology & Production
  - Music, Sound and Technology
  - Music & Technology
  - Biotechnology / Biomedical Sciences / Physics
  - Molecular Biology and Biotechnology
  - Business + Engineering
  - Biology, Biotechnology, Biomedical Sciences, Medicine (Spain)
  - MEng Architectural Environment Engineering with Industrial Placement Year
  - Architectural Engineering
  - Bachelor in Engineering
  - Engineering with Placement Year H106
  - General Engineering with a Foundation Year (H101)
  - Biotechnology, Biomedicine, Genetics, Veterinary
  - Biomedical Engineering

Business (58):
  - Business, Communication, International Business, Geopolitics and International Relations
  - Management
  - Business Admistration & Artificial Inteligence for Business
  - Bussines & Finance
  - Business
  - Finance
  - Business Admistration
  - Business Administration in Aviation
  - International Business, Finance & Economics w IE (N1N4)
  - Economics with Finance (LN13)
  - Business Administration
  - International Business IBA
  - International Business
  - International BBA - Business Management
  - Business Management with Entrepreneurship and Innovation
  - Business & Management
  - Business Management & Human Resource Management
  - Economics and Finance
  - Management BSB (Kelley)
  - Management
  - Mathematics & Finance
  - Mathematics & Business
  - Global BBA
  - Bachelor in Management
  - Bachelor Economics & Business Economics (IBEB)
  - Master of Finance
  - Global Business Track
  - BSc International Business Administration
  - International Business N120
  - Business with Work Placements C110
  - Business Management with Year in Industry N201
  - International BBA
  - DG BA with AI
  - Pre-Business
  - Business Administration and Management and Law
  - Grado en Administración y dirección de empresas
  - ADE + Finance and Accounting
  - Business Administration, Film Making, International Business & Relations, Management, Marketing, Public Relations, Toruism, Transportation & Logistics
  - Bachelor in International Business
  - International Business Management with Foundation Year N123
  - Business Management N200
  - Honours Science and Business, Co-op
  - Modern Languages (One Language) and Business Management R9N2
  - IAP
  - International business & Economics
  - Accountingm Business, Finance & Management
  - Business, Economics & Finance with Placement year
  - Business with Professional Placement
  - Business Economics
  - Dual Degree in Business Administration and International Relations
  - Accounting, Business, Finance & Management
  - Business Finance & Economics with a Placement Year
  - Business, Management & Economics
  - Business Administration & Marketing
  - Global Business
  - Business & Management N201
  - International Management
  - Global BBA Singapoore

Economics & Econometrics (4):
  - Bachelor of Economics
  - Economics
  - Busainess Economics with Industrial Experience
  - International Buasines and Economics

Psychology (9):
  - Behavioral & Biological Sciences
  - Cognitive Science
  - Psychology
  - Psychology with Cognitive Neuroscience (C808)
  - Psychology with Neuropsychology (C801)
  - Psychology with Human Neuroscience (CC89)
  - Psychology (C800)
  - Cognitive Science + AI
  - Psychology with Cognitive Neuroscience (Including Placement Year) (C809)

Politics (4):
  - International Relations/Affairs
  - International Relations
  - Doble Grado Derecho y Relaciones Internacionales
  - Grado en Economía y Relaciones Internacionales

Sociology (1):
  - Criminology

Social Policy (3):
  - Refugees and Foced Migration Studies
  - Public Health
  - Health Services Administration

Biological (19):
  - Biological Science
  - Biological Science Pre-medical Sciences
  - Biology
  - Pre-Biology Zoology, Botany and Econ
  - Biology-Medical Biology
  - Genomics and Molecular Genetics
  - Molecular and Cellular Biology: Genetics
  - Biochemistry and Molecular Biology
  - Diagnostic Genetic Science
  - Genetics
  - Biological Sciences
  - Biology - Molecular and Cell Biology and Physiology
  - Microbiology
  - Biomedical Sciences
  - DG Biochemistry & Molecular Biology
  - Cellular And Molecular Biomedical Science (Major)
  - Biology and Heatlh Sciencies
  - Physiology
  - Biomedical Science

Medicine (5):
  - Medicine
  - Biochemistry with Medical Biochemistry (MSci)
  - Chemistry with Biomedicine
  - Applied Medical Sciences
  - Medical Sciences

Nursing (1):
  - Nursing

Veterinary Science (1):
  - Equine Wealthfare/Science

Law (3):
  - Law
  - Law Foundation
  - International Foundation in Humanities and Law

Architecture (1):
  - Architecture

Music (4):
  - Pop Music: Guitar
  - Instrumental Arts: Guitar
  - Music Production & Recording Arts
  - Digital Music

Performing Arts (9):
  - Drama - Acting
  - Film & Video
  - Film
  - Radio/Television/Film
  - Dramatic Writing
  - Creative Writing, Film
  - Screenwriting
  - Writing for Screen and Television
  - Film & Television

Arts & Humanities (3):
  - College of Arts & Sciences
  - Bachelor of Arts
  - Creative Writing

Natural Sciences (5):
  - Sport and Exercise Sciences - 3FTBSc (Hons)
  - Maastricht Science Program
  - Life Sciences
  - Mathematica & Physical Sciences
  - Sciences

Mathematics (6):
  - Mathematics or Physics
  - Mathematical Computation
  - Applied Mathematics
  - Mathematicis & Physics
  - Mathematics G100
  - Mathematics

Physics (4):
  - Physics
  - Physics with Theoretical Physics
  - Theoretical Physics
  - Astronomy

Chemistry (2):
  - Biochemistry
  - Chemistry

Sports-related Subjects (4):
  - BSc (Hons) Applied Sports Science
  - BSc Sport and Exercise Science with a Placement Year
  - BSc Sport and Exercise Science with Professional Placement or Study Abroad
  - Applied Sport Science - 4FTBSc (Hons)

Art & Design (1):
  - Diseño de producto

### Universidades en comun df_students/df_qs

In [11]:
from src.merge_students_qs import show_inner_universities

show_inner_universities(df_students, df_qs)

Universidades únicas students: 214
Universidades únicas qs: 1758
Universidades en común: 113

In [12]:
from src.merge_students_qs import merge_students_qs

df_pred = merge_students_qs(df_students, df_qs)

In [13]:
df_pred.head()

,school_curriculum,school_grade,gpa,toefl,sat,profile_score,peak,university,country,degree,admitted,sat_required,qs_score
0,BASE 7,33.0,3.5,102,1000.0,9,0,AMSTERDAM UNIVERSITY OF APPLIED SCIENCE,NETHERLANDS,Business,1.0,1,NaN
1,BASE 7,33.0,3.5,102,1000.0,9,0,AMSTERDAM UNIVERSITY OF APPLIED SCIENCE,NETHERLANDS,Politics,1.0,1,NaN
2,BASE 7,33.0,3.5,102,1000.0,9,0,IE UNIVERISTY,SPAIN,Business,1.0,1,NaN
3,BASE 7,33.0,3.5,102,1000.0,9,0,IE UNIVERISTY,SPAIN,Politics,1.0,1,NaN
4,BASE 7,33.0,3.5,102,1000.0,9,0,UNIVERSITY EUROPEA,SPAIN,Business,1.0,1,NaN

In [14]:
df_pred.shape

(751, 13)